<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Machine [
<!ELEMENT Machine (PunctChar*, Field*, FileChannel*, Register*, RegisterArray*, ConditionBit*, RAM*, Set*, Test*, Increment*, Shift*, Logical*, Arithmetic*, Branch*, TransferRtoR*, TransferRtoA*, TransferAtoR*, Decode*, SetCondBit*, IO*, MemoryAccess*, End, Comment*, EQU*, FetchSequence, MachineInstruction*, HighlightingInfo?, LoadingInfo?, IndexingInfo?, ProgramCounterInfo?, ModuleWindowsInfo?) >
<!ATTLIST Machine name CDATA "unnamed">
<!ELEMENT PunctChar EMPTY>
<!ATTLIST PunctChar char CDATA #REQUIRED use  (symbol|token|label|comment|pseudo|illegal) #REQUIRED>
<!ELEMENT Field (FieldValue*)>
<!ATTLIST Field name CDATA #REQUIRED type  (required|optional|ignored) #REQUIRED numBits CDATA #REQUIRED relativity (absolute|pcRelativePreIncr|pcRelativePostIncr) #REQUIRED defaultValue CDATA #REQUIRED signed (true|false) #REQUIRED id ID #REQUIRED>
<!ELEMENT FieldValue EMPTY>
<!ATTLIST FieldValue name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT FileChannel EMPTY>
<!ATTLIST FileChannel file CDATA #REQUIRED id CDATA #REQUIRED>
<!ELEMENT Register EMPTY>
<!ATTLIST Register name CDATA #REQUIRED width CDATA #REQUIRED initialValue CDATA #REQUIRED readOnly (true|false) "false" id ID #REQUIRED>
<!ELEMENT RegisterArray (Register+)>
<!ATTLIST RegisterArray name CDATA #REQUIRED width CDATA #REQUIRED length CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT ConditionBit EMPTY>
<!ATTLIST ConditionBit name CDATA #REQUIRED bit CDATA #REQUIRED register IDREF #REQUIRED halt (true|false) "false" id ID #REQUIRED>
<!ELEMENT RAM EMPTY>
<!ATTLIST RAM name CDATA #REQUIRED length CDATA #REQUIRED id ID #REQUIRED cellSize CDATA "8">
<!ELEMENT Increment EMPTY>
<!ATTLIST Increment name CDATA #REQUIRED register IDREF #REQUIRED overflowBit IDREF #IMPLIED carryBit IDREF #IMPLIED delta CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Arithmetic EMPTY>
<!ATTLIST Arithmetic name CDATA #REQUIRED type (ADD|SUBTRACT|MULTIPLY|DIVIDE) #REQUIRED source1 IDREF #REQUIRED source2 IDREF #REQUIRED destination IDREF #REQUIRED overflowBit IDREF #IMPLIED  carryBit IDREF #IMPLIED  id ID #REQUIRED>
<!ELEMENT TransferRtoR EMPTY>
<!ATTLIST TransferRtoR name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT TransferRtoA EMPTY>
<!ATTLIST TransferRtoA name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED index IDREF #REQUIRED indexStart CDATA #IMPLIED indexNumBits CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT TransferAtoR EMPTY>
<!ATTLIST TransferAtoR name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED index IDREF #REQUIRED indexStart CDATA #IMPLIED indexNumBits CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT Shift EMPTY>
<!ATTLIST Shift name CDATA #REQUIRED source IDREF #REQUIRED destination IDREF #REQUIRED type (logical | arithmetic | cyclic) #REQUIRED direction (right | left) #REQUIRED distance CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Branch EMPTY>
<!ATTLIST Branch name CDATA #REQUIRED amount CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Logical EMPTY>
<!ATTLIST Logical name CDATA #REQUIRED source1 IDREF #REQUIRED source2 IDREF #REQUIRED destination IDREF #REQUIRED type (AND | OR | NAND | NOR | XOR | NOT) #REQUIRED id ID #REQUIRED>
<!ELEMENT Set EMPTY>
<!ATTLIST Set name CDATA #REQUIRED register IDREF #REQUIRED start CDATA #REQUIRED numBits CDATA #REQUIRED value CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Test EMPTY >
<!ATTLIST Test name CDATA #REQUIRED register IDREF #REQUIRED start CDATA #REQUIRED numBits CDATA #REQUIRED comparison (EQ | NE | LT | GT | LE | GE ) #REQUIRED value CDATA #REQUIRED omission CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Decode EMPTY >
<!ATTLIST Decode name CDATA #REQUIRED ir IDREF #REQUIRED id ID #REQUIRED>
<!ELEMENT IO EMPTY >
<!ATTLIST IO name CDATA #REQUIRED direction (input | output) #REQUIRED type (integer | ascii | unicode) #REQUIRED buffer IDREF #REQUIRED connection CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT MemoryAccess EMPTY >
<!ATTLIST MemoryAccess name CDATA #REQUIRED direction (read | write ) #REQUIRED memory IDREF #REQUIRED data IDREF #REQUIRED address IDREF #REQUIRED id ID #REQUIRED>
<!ELEMENT SetCondBit EMPTY >
<!ATTLIST SetCondBit name CDATA #REQUIRED bit IDREF #REQUIRED value (0 | 1) #REQUIRED id ID #REQUIRED>
<!ELEMENT End EMPTY>
<!ATTLIST End id ID #REQUIRED>
<!ELEMENT Comment EMPTY>
<!ATTLIST Comment name CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Microinstruction EMPTY>
<!ATTLIST Microinstruction microRef IDREF #REQUIRED>
<!ELEMENT MachineInstruction (Microinstruction*)>
<!ATTLIST MachineInstruction name CDATA #REQUIRED opcode CDATA #REQUIRED instructionFormat CDATA #REQUIRED assemblyFormat CDATA #REQUIRED instructionColors CDATA #REQUIRED assemblyColors CDATA #REQUIRED>
<!ELEMENT FetchSequence (Microinstruction*) >
<!ELEMENT EQU EMPTY>
<!ATTLIST EQU name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT HighlightingInfo (RegisterRAMPair*)>
<!ELEMENT RegisterRAMPair EMPTY>
<!ATTLIST RegisterRAMPair register IDREF #REQUIRED ram IDREF #REQUIRED dynamic (true|false) #REQUIRED>
<!ELEMENT LoadingInfo EMPTY>
<!ATTLIST LoadingInfo ram IDREF #IMPLIED startingAddress CDATA "0">
<!ELEMENT IndexingInfo EMPTY>
<!ATTLIST IndexingInfo indexFromRight CDATA "false">
<!ELEMENT ProgramCounterInfo EMPTY>
<!ATTLIST ProgramCounterInfo programCounter IDREF #REQUIRED>
<!ELEMENT ModuleWindowsInfo ((RegisterWindowInfo | RegisterArrayWindowInfo | RAMWindowInfo)*) >
<!ELEMENT RegisterWindowInfo EMPTY>
<!ATTLIST RegisterWindowInfo top CDATA "50" left CDATA "50" width CDATA "300" height CDATA "150" base (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode)  "Decimal">
<!ELEMENT RegisterArrayWindowInfo EMPTY>
<!ATTLIST RegisterArrayWindowInfo array IDREF #REQUIRED top CDATA "50" left CDATA "50" width CDATA "300" height CDATA "150" base (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode) "Decimal">
<!ELEMENT RAMWindowInfo EMPTY>
<!ATTLIST RAMWindowInfo ram IDREF #REQUIRED cellSize CDATA "1" top CDATA "50" left CDATA "50" width CDATA "450" height CDATA "450" contentsbase (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode) "Decimal" addressbase (Decimal|Binary|Hexadecimal) "Decimal">
]>

<Machine name="Updated machine.CPU" >
	<!--............. Punctuation Options .............-->
	<PunctChar char="!" use="symbol" />
	<PunctChar char="#" use="symbol" />
	<PunctChar char="$" use="symbol" />
	<PunctChar char="%" use="symbol" />
	<PunctChar char="&amp;" use="symbol" />
	<PunctChar char="^" use="symbol" />
	<PunctChar char="_" use="symbol" />
	<PunctChar char="`" use="symbol" />
	<PunctChar char="*" use="symbol" />
	<PunctChar char="?" use="symbol" />
	<PunctChar char="@" use="symbol" />
	<PunctChar char="~" use="symbol" />
	<PunctChar char="+" use="symbol" />
	<PunctChar char="-" use="symbol" />
	<PunctChar char="(" use="token" />
	<PunctChar char=")" use="token" />
	<PunctChar char="," use="token" />
	<PunctChar char="/" use="token" />
	<PunctChar char="=" use="token" />
	<PunctChar char="[" use="token" />
	<PunctChar char="\" use="token" />
	<PunctChar char="]" use="token" />
	<PunctChar char="{" use="token" />
	<PunctChar char="|" use="token" />
	<PunctChar char="}" use="token" />
	<PunctChar char="." use="pseudo" />
	<PunctChar char=":" use="label" />
	<PunctChar char=";" use="comment" />

	<!--......... machine instruction fields ............-->
	<Field name="REGISTER" type="required" numBits="16" relativity="absolute" signed="false" defaultValue="0" id="model.Field72f53b90">
	</Field>
	<Field name="ADDR" type="required" numBits="12" relativity="absolute" signed="false" defaultValue="0" id="model.Field395ce27f">
	</Field>
	<Field name="OP" type="required" numBits="4" relativity="absolute" signed="false" defaultValue="0" id="model.Field258d059b">
	</Field>

	<!--............. FileChannels .................-->
	<!-- none -->

	<!--............. registers .....................-->
	<Register name="AC" width="16" initialValue="0" readOnly="false" id="model.module.Register4979b409" />
	<Register name="AR" width="12" initialValue="0" readOnly="false" id="model.module.Register26415ad3" />
	<Register name="DR" width="16" initialValue="0" readOnly="false" id="model.module.Register5b5b0ea7" />
	<Register name="E" width="1" initialValue="0" readOnly="false" id="model.module.Register2b35900e" />
	<Register name="I" width="1" initialValue="0" readOnly="false" id="model.module.Register2fe8b09d" />
	<Register name="IR" width="16" initialValue="0" readOnly="false" id="model.module.Register3d3e071" />
	<Register name="PC" width="12" initialValue="0" readOnly="false" id="model.module.Registerfee89a" />
	<Register name="S" width="1" initialValue="0" readOnly="false" id="model.module.Register7ccad6b" />

	<!--............. register arrays ...............-->
	<!-- none -->

	<!--............. condition bits ................-->
	<ConditionBit name="CARRY-BIT" bit="0" register="model.module.Register2b35900e" halt="false" id="model.module.ConditionBit6dca9957" />
	<ConditionBit name="HALT-BIT" bit="0" register="model.module.Register7ccad6b" halt="true" id="model.module.ConditionBit71062cf7" />

	<!--............. rams ..........................-->
	<RAM name="MAIN" length="4096" cellSize="16" id="model.module.RAM6cba075" />

	<!--............. set ...........................-->
	<!-- none -->

	<!--............. test ..........................-->
	<Test name="DR!=0" register="model.module.Register5b5b0ea7" start="0" numBits="16" comparison="NE" value="0" omission="1" id="model.microinstruction.Test7138fb84" />

	<!--............. increment .....................-->
	<Increment name="INCR-AC" register="model.module.Register4979b409" delta="1" id="model.microinstruction.Increment640ef232" />
	<Increment name="INCR-DR" register="model.module.Register5b5b0ea7" delta="1" id="model.microinstruction.Increment9594239" />
	<Increment name="INCR-PC" register="model.module.Registerfee89a" delta="1" id="model.microinstruction.Increment5d37dfc5" />

	<!--............. shift .........................-->
	<!-- none -->

	<!--............. logical .......................-->
	<Logical name="AC&lt;-AC and DR" type="AND" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" id="model.microinstruction.Logical5509175f" />
	<Logical name="AC&lt;-AC nand DR" type="NAND" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" id="model.microinstruction.Logical362323cc" />
	<Logical name="AC&lt;-AC nor DR" type="NOR" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" id="model.microinstruction.Logical1a910a29" />
	<Logical name="AC&lt;-AC or DR" type="OR" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" id="model.microinstruction.Logical736b80be" />
	<Logical name="AC&lt;-AC xor DR" type="XOR" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" id="model.microinstruction.Logical6ec5d263" />
	<Logical name="AC&lt;-AC'" type="NOT" source1="model.module.Register4979b409" source2="model.module.Register4979b409" destination="model.module.Register4979b409" id="model.microinstruction.Logical4157a134" />

	<!--............. arithmetic ....................-->
	<Arithmetic name="AC&lt;-AC*DR" type="MULTIPLY" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" carryBit="model.module.ConditionBit6dca9957" id="model.microinstruction.Arithmetic54dbbfda" />
	<Arithmetic name="AC&lt;-AC+DR" type="ADD" source1="model.module.Register4979b409" source2="model.module.Register5b5b0ea7" destination="model.module.Register4979b409" carryBit="model.module.ConditionBit6dca9957" id="model.microinstruction.Arithmetic53053b75" />

	<!--............. branch ........................-->
	<!-- none -->

	<!--............. transferRtoR ..................-->
	<TransferRtoR name="AR&lt;-IR(4-15)" source="model.module.Register3d3e071" srcStartBit="4" dest="model.module.Register26415ad3" destStartBit="0" numBits="12" id="model.microinstruction.TransferRtoR7c442fdb" />
	<TransferRtoR name="AR&lt;-PC" source="model.module.Registerfee89a" srcStartBit="0" dest="model.module.Register26415ad3" destStartBit="0" numBits="12" id="model.microinstruction.TransferRtoR3c52bcfa" />

	<!--............. transferRtoA ..................-->
	<!-- none -->

	<!--............. transferAtoR ..................-->
	<!-- none -->

	<!--............. decode ........................-->
	<Decode name="DECODE-IR" ir="model.module.Register3d3e071" id="model.microinstruction.Decode4070e445" />

	<!--............. set condition bit .............-->
	<SetCondBit name="HALT" bit="model.module.ConditionBit71062cf7" value="1" id="model.microinstruction.SetCondBit3ad4a1ad" />

	<!--............. io ............................-->
	<IO name="INPUT" direction="input" type="integer" buffer="model.module.Register4979b409" connection="[Console]" id="model.microinstruction.IO67b36bdb" />
	<IO name="OUTPUT" direction="output" type="integer" buffer="model.module.Register4979b409" connection="[Console]" id="model.microinstruction.IO4eafbebb" />

	<!--............. memory access .................-->
	<MemoryAccess name="AC&lt;-Main[AR]" direction="read" memory="model.module.RAM6cba075" data="model.module.Register4979b409" address="model.module.Register26415ad3" id="model.microinstruction.MemoryAccess93a39e7" />
	<MemoryAccess name="DR&lt;-Main[AR]" direction="read" memory="model.module.RAM6cba075" data="model.module.Register5b5b0ea7" address="model.module.Register26415ad3" id="model.microinstruction.MemoryAccess167c28a4" />
	<MemoryAccess name="IR&lt;-MAIN[AR]" direction="read" memory="model.module.RAM6cba075" data="model.module.Register3d3e071" address="model.module.Register26415ad3" id="model.microinstruction.MemoryAccess6a6d6403" />
	<MemoryAccess name="Main[AR]&lt;-AC" direction="write" memory="model.module.RAM6cba075" data="model.module.Register4979b409" address="model.module.Register26415ad3" id="model.microinstruction.MemoryAccess59845593" />
	<MemoryAccess name="Main[AR]&lt;-DR" direction="write" memory="model.module.RAM6cba075" data="model.module.Register5b5b0ea7" address="model.module.Register26415ad3" id="model.microinstruction.MemoryAccess76552328" />

	<!--............. end ...........................-->
	<End id="model.microinstruction.End1a9ba45" />

	<!--............. comment ...........................-->
	<!-- none -->

	<!--............. global equs ..................-->
	<!-- none -->

	<!--............. fetch sequence ................-->
	<FetchSequence>
		<Microinstruction microRef="model.microinstruction.TransferRtoR3c52bcfa" />
		<Microinstruction microRef="model.microinstruction.MemoryAccess6a6d6403" />
		<Microinstruction microRef="model.microinstruction.Increment5d37dfc5" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR7c442fdb" />
		<Microinstruction microRef="model.microinstruction.Decode4070e445" />
	</FetchSequence>

	<!--............. machine instructions ..........-->

	<MachineInstruction name="ISZ" opcode="c" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#8ecaa4 #cb8b8b" assemblyColors="#8ecaa4 #cb8b8b" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Increment9594239" />
		<Microinstruction microRef="model.microinstruction.MemoryAccess76552328" />
		<Microinstruction microRef="model.microinstruction.Test7138fb84" />
		<Microinstruction microRef="model.microinstruction.Increment5d37dfc5" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="MUL" opcode="8" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#f5dfe7 #9beff2" assemblyColors="#f5dfe7 #9beff2" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Arithmetic54dbbfda" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="NAND" opcode="7" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#fcaeb8 #b4f2c1" assemblyColors="#fcaeb8 #b4f2c1" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Logical362323cc" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="NOR" opcode="5" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#af88af #b5ec82" assemblyColors="#af88af #b5ec82" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Logical1a910a29" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="XOR" opcode="3" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#82bc84 #ddd78b" assemblyColors="#82bc84 #ddd78b" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Logical6ec5d263" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="OR" opcode="1" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#938cc1 #b8d49c" assemblyColors="#938cc1 #b8d49c" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Logical736b80be" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="AND" opcode="0" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#8af889 #d494f4" assemblyColors="#8af889 #d494f4" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Logical5509175f" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="LDA" opcode="4" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#def2ce #b7e29c" assemblyColors="#def2ce #b7e29c" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess93a39e7" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="INC" opcode="e020" instructionFormat="REGISTER" assemblyFormat="REGISTER" instructionColors="#c58fd8" assemblyColors="#c58fd8" >
		<Microinstruction microRef="model.microinstruction.Increment640ef232" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="CMA" opcode="e200" instructionFormat="REGISTER" assemblyFormat="REGISTER" instructionColors="#bb96a4" assemblyColors="#bb96a4" >
		<Microinstruction microRef="model.microinstruction.Logical4157a134" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="ADD" opcode="2" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#abb1d5 #d5fbab" assemblyColors="#abb1d5 #d5fbab" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess167c28a4" />
		<Microinstruction microRef="model.microinstruction.Arithmetic53053b75" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="STA" opcode="6" instructionFormat="OP ADDR" assemblyFormat="OP ADDR" instructionColors="#f3c4cc #b694cf" assemblyColors="#f3c4cc #b694cf" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess59845593" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="HLT" opcode="e001" instructionFormat="REGISTER" assemblyFormat="REGISTER" instructionColors="#bfedb2" assemblyColors="#bfedb2" >
		<Microinstruction microRef="model.microinstruction.SetCondBit3ad4a1ad" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="OUT" opcode="f400" instructionFormat="REGISTER" assemblyFormat="REGISTER" instructionColors="#e0b9ae" assemblyColors="#e0b9ae" >
		<Microinstruction microRef="model.microinstruction.IO4eafbebb" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<MachineInstruction name="INP" opcode="f800" instructionFormat="REGISTER" assemblyFormat="REGISTER" instructionColors="#bda88e" assemblyColors="#bda88e" >
		<Microinstruction microRef="model.microinstruction.IO67b36bdb" />
		<Microinstruction microRef="model.microinstruction.End1a9ba45" />
	</MachineInstruction>

	<!--............. highlighting info .............-->
	<HighlightingInfo>
	</HighlightingInfo>

	<!--............. loading info ..................-->
	<LoadingInfo ram="model.module.RAM6cba075" startingAddress="0" />

	<!--............. indexing info ............-->
	<IndexingInfo indexFromRight="false" />

	<!--............. program counter info ..................-->

</Machine>
